[
  {
    "bookurl": "http://franklin.library.upenn.edu/record.html?id=FRANKLIN_6332962",
    "image": "//syndetics.com/index.aspx?isbn=9780199978335/LC.GIF&client=springshare",
    "articletitle": "",
    "articlein": "",
    "booktitle": "&quot;We Are Who We Say We Are&quot; : a Black Family's Search For Home Across the Atlantic World",
    "author1url": "http://www.history.upenn.edu/people/faculty/mary-frances-berry",
    "author1": "Mary Berry Frances",
    "author2url": "",
    "andauthor2": "",
    "author2": "",
    "author3url": "",
    "andauthor3": "",
    "author3": "",
    "gburl": "",
    "gbtext": "",
    "pubdate": "2015"
  },
  {
    "bookurl": "http://franklin.library.upenn.edu/record.html?id=FRANKLIN_6105195",
    "image": "//books.google.com/books/content?id=_vpaAgAAQBAJ&printsec=frontcover&img=1&zoom=1&",
    "articletitle": "",
    "articlein": "",
    "booktitle": "Promoting Racial Literacy: Differences that Make a Difference",
    "author1url": "http://scholar.gse.upenn.edu/stevenson",
    "author1": "Howard C. Stevenson",
    "author2url": "",
    "andauthor2": "",
    "author2": "",
    "author3url": "",
    "andauthor3": "",
    "author3": "",
    "gburl": "",
    "gbtext": "",
    "pubdate": "2014"
  },
  {
    "bookurl": "http://franklin.library.upenn.edu/record.html?id=FRANKLIN_5957720",
    "image": "//goo.gl/NGvKFS",
    "articletitle": "",
    "articlein": "",
    "booktitle": "A Place That Matters Yet: John Gubbin's MuseumAfrica in the Postcolonial World",
    "author1url": "",
    "author1": "Sara Byala",
    "author2url": "",
    "andauthor2": "",
    "author2": "",
    "author3url": "",
    "andauthor3": "",
    "author3": "",
    "gburl": "http://goo.gl/bdsAFM",
    "gbtext": "Also Google Books",
    "pubdate": "2013"
  },
  {
    "bookurl": "http://dla.library.upenn.edu/dla/franklin/record.html?id=FRANKLIN_5408304",
    "image": "//syndetics.com/index.aspx?isbn=9780199922680/LC.GIF&client=springshare",
    "articletitle": "",
    "articlein": "",
    "booktitle": "American Slavery: A Very Short Introduction",
    "author1url": "https://africana.sas.upenn.edu/department/heather-williams",
    "author1": "Heather Andrea Williams",
    "author2url": "",
    "andauthor2": "",
    "author2": "",
    "author3url": "",
    "andauthor3": "",
    "author3": "",
    "gburl": "",
    "gbtext": "",
    "pubdate": "2014"
  },
  {
    "bookurl": "http://www.amazon.com/Behind-Academic-Curtain-Success-Happiness/dp/022606610X/",
    "image": "//goo.gl/W4ojLi",
    "articletitle": "",
    "articlein": "",
    "booktitle": "Behind the Academic Curtain: How to Find Success and Happiness with a PhD",
    "author1url": "http://www.ssc.upenn.edu/~fff/",
    "author1": "Frank F. Furstenberg, Jr.",
    "author2url": "",
    "andauthor2": "",
    "author2": "",
    "author3url": "",
    "andauthor3": "",
    "author3": "",
    "gburl": "http://goo.gl/ge15TJ",
    "gbtext": "Also Google Books",
    "pubdate": "2013"
  },
  {
    "bookurl": "http://franklin.library.upenn.edu/record.html?id=FRANKLIN_6243866",
    "image": "//books.google.com/books/content?id=kJf5AwAAQBAJ&printsec=frontcover&img=1&zoom=1&",
    "articletitle": "",
    "articlein": "",
    "booktitle": "A Question of Tradition: Women Poets in Yiddish",
    "author1url": "http://ccat.sas.upenn.edu/german/people/kathryn-hellerstein",
    "author1": "Kathryn Hellerstein",
    "author2url": "",
    "andauthor2": "",
    "author2": "",
    "author3url": "",
    "andauthor3": "",
    "author3": "",
    "gburl": "",
    "gbtext": "",
    "pubdate": "2014"
  },
  {
    "bookurl": "http://franklin.library.upenn.edu/record.html?id=FRANKLIN_5972994",
    "image": "//goo.gl/i3vlxl",
    "articletitle": "",
    "articlein": "",
    "booktitle": "The Mormon Quest for Glory: The Religious World of the Latter-Day Saints",
    "author1url": "http://ccat.sas.upenn.edu/~mhammarb/",
    "author1": "Melvyn Hammarberg",

    "author2url": "",
    "andauthor2": "",
    "author2": "",
    "author3url": "",
    "andauthor3": "",
    "author3": "",
    "gburl": "http://goo.gl/cHkTJf",
    "gbtext": "Also Google Books",
    "pubdate": "2013"
  },
  {
    "bookurl": "http://franklin.library.upenn.edu/record.html?id=FRANKLIN_6262962",
    "image": "//books.google.com/books/content?id=gnTCoAEACAAJ&printsec=frontcover&img=1&zoom=1",
    "articletitle": "",
    "articlein": "",
    "booktitle": "Caught : The Prison State and the Lockdown of American Politics",
    "author1url": "https://www.sas.upenn.edu/polisci/people/standing-faculty/marie-gottschalk-0",
    "author1": "Marie Gottschalk",
    "author2url": "",
    "andauthor2": "",
    "author2": "",
    "author3url": "",
    "andauthor3": "",
    "author3": "",
    "gburl": "",
    "gbtext": "",
    "pubdate": "2015"
  },
  {
    "bookurl": "http://franklin.library.upenn.edu/record.html?id=FRANKLIN_6333652",
    "image": "//books.google.com/books/content?id=VNDYBAAAQBAJ&printsec=frontcover&img=1&zoom=1&",
    "articletitle": "",
    "articlein": "",
    "booktitle": "China's Challenges",
    "author1url": "https://www.law.upenn.edu/cf/faculty/jdelisle/",
    "author1": "Jacques deLisle",
    "author2url": "https://www.sas.upenn.edu/polisci/people/standing-faculty/avery-goldstein",
    "andauthor2": " and ",
    "author2": "Avery Goldstein",
    "author3url": "",
    "andauthor3": "",
    "author3": "",
    "gburl": "",
    "gbtext": "",
    "pubdate": "2015"
  },
  {
    "bookurl": "http://franklin.library.upenn.edu/record.html?id=FRANKLIN_6264447",
    "image": "//books.google.com/books/content?id=SIk3AwAAQBAJ&printsec=frontcover&img=1&zoom=1&",
    "articletitle": "",
    "articlein": "",
    "booktitle": "Sun, Sea, and Sound: Music and Tourism in the Circum-Caribbean",
    "author1url": "https://www.sas.upenn.edu/music/people/standing-faculty/timothy-rommen",
    "author1": "Timothy Rommen",
    "author2url": "",
    "andauthor2": " and ",
    "author2": "Daniel Tannehill Neely",
    "author3url": "",
    "andauthor3": "",
    "author3": "",
    "gburl": "",
    "gbtext": "",
    "pubdate": "2014"
  },
  {
    "bookurl": "http://franklin.library.upenn.edu/record.html?id=FRANKLIN_6244570",
    "image": "//books.google.com/books/content?id=xinnAwAAQBAJ&printsec=frontcover&img=1&zoom=1&",
    "articletitle": "",
    "articlein": "",
    "booktitle": "Race for Paradise: An Islamic History of the Crusades",
    "author1url": "http://www.sas.upenn.edu/nelc/people/facultyProfiles.html",
    "author1": "Paul M. Cobb",
    "author2url": "",
    "andauthor2": "",
    "author2": "",
    "author3url": "",
    "andauthor3": "",
    "author3": "",
    "gburl": "",
    "gbtext": "",
    "pubdate": "2014"
  },
  {
    "bookurl": "http://franklin.library.upenn.edu/record.html?id=FRANKLIN_6327203",
    "image": "//books.google.com/books/content?id=FDwlBQAAQBAJ&printsec=frontcover&img=1&zoom=1&",
    "articletitle": "",
    "articlein": "",
    "booktitle": "Raising Race Questions: Whiteness and Inquiry in Education",
    "author1url": "http://www.gse.upenn.edu/equity/content/researchers-and-staff",
    "author1": "Ali Michael",
    "author2url": "",
    "andauthor2": "",
    "author2": "",
    "author3url": "",
    "andauthor3": "",
    "author3": "",
    "gburl": "",
    "gbtext": "",
    "pubdate": "2015"
  },
  {
    "bookurl": "http://franklin.library.upenn.edu/record.html?id=FRANKLIN_6249256",
    "image": "//books.google.com/books/content?id=LelKYgEACAAJ&printsec=frontcover&img=1&zoom=1",
    "articletitle": "",
    "articlein": "",
    "booktitle": "Routledge Guide to Descartes' Meditations",
    "author1url": "https://philosophy.sas.upenn.edu/faculty/hatfield",
    "author1": "Gary Hatfield",
    "author2url": "",
    "andauthor2": "",
    "author2": "",
    "author3url": "",
    "andauthor3": "",
    "author3": "",
    "gburl": "",
    "gbtext": "",
    "pubdate": "2014"
  },
  {
    "bookurl": "http://franklin.library.upenn.edu/record.html?id=FRANKLIN_5953598",
    "image": "//goo.gl/9pM6mc",
    "articletitle": "",
    "articlein": "",
    "booktitle": "Reading Piers Plowman",
    "author1url": "http://www.english.upenn.edu/People/EmilySteiner",
    "author1": "Emily Steiner",
    "author2url": "",
    "andauthor2": "",
    "author2": "",
    "author3url": "",
    "andauthor3": "",
    "author3": "",
    "gburl": "http://goo.gl/368AgS",
    "gbtext": "Also Google Books",
    "pubdate": "2013"
  },
  {
    "bookurl": "http://goo.gl/5yXGBN",
    "image": "//goo.gl/AO9tPE",
    "articletitle": "",
    "articlein": "",
    "booktitle": "Thin Description: Ethnography and the African Hebrew Israelites of Jerusalem",
    "author1url": "http://goo.gl/9BV2Ru",
    "author1": "John L. Jackson",
    "author2url": "",
    "andauthor2": "",
    "author2": "",
    "author3url": "",
    "andauthor3": "",
    "author3": "",
    "gburl": "http://goo.gl/BnlJEe",
    "gbtext": "Also Google Books",
    "pubdate": "2013"
  },
  {
    "bookurl": "http://franklin.library.upenn.edu/record.html?id=FRANKLIN_6296783",
    "image": "//books.google.com/books/content?id=JrMyBQAAQBAJ&printsec=frontcover&img=1&zoom=1&",
    "articletitle": "",
    "articlein": "",
    "booktitle": "A Tale of Two Plantations: Slave Life and Labor in Jamaica and Virginia",
    "author1url": "http://www.history.upenn.edu/people/emeritus/richard-s-dunn",
    "author1": "Richard S. Dunne",
    "author2url": "",
    "andauthor2": "",
    "author2": "",
    "author3url": "",
    "andauthor3": "",
    "author3": "",
    "gburl": "",
    "gbtext": "",
    "pubdate": "2014"
  },
  {
    "bookurl": "http://franklin.library.upenn.edu/record.html?id=FRANKLIN_6242715",
    "image": "http://books.google.com/books/content?id=zcE_AwAAQBAJ&printsec=frontcover&img=1&zoom=1",
    "articletitle": "",
    "articlein": "",
    "booktitle": "Event History and Survival Analysis",
    "author1url": "https://sociology.sas.upenn.edu/paul_allison",
    "author1": "Paul David Allison",
    "author2url": "",
    "andauthor2": "",
    "author2": "",
    "author3url": "",
    "andauthor3": "",
    "author3": "",
    "gburl": "",
    "gbtext": "",
    "pubdate": "2014"
  },
  {
    "bookurl": "http://franklin.library.upenn.edu/record.html?id=FRANKLIN_6067987",
    "image": "//books.google.com/books/content?id=ZO8EnwEACAAJ&printsec=frontcover&img=1&zoom=1",
    "articletitle": "",
    "articlein": "",
    "booktitle": "Transects: 100 Years of Landscape Architecture and Regional Planning at the School of Design of the University of Pennsylvania",
    "author1url": "https://www.design.upenn.edu/landscape-architecture/people/richard-weller-0",
    "author1": "Richard Weller",
    "author2url": "",
    "andauthor2": "",
    "author2": "",
    "author3url": "",
    "andauthor3": "",
    "author3": "",
    "gburl": "",
    "gbtext": "",
    "pubdate": "2014"
  },
  {
    "bookurl": "http://franklin.library.upenn.edu/record.html?id=FRANKLIN_6339439",
    "image": "//books.google.com/books/content?id=RsWTBQAAQBAJ&printsec=frontcover&img=1&zoom=1&",
    "articletitle": "",
    "articlein": "",
    "booktitle": "Tying the Autocrat's Hands: The Rise of the Rule of Law in China",
    "author1url": "https://www.sas.upenn.edu/polisci/people/standing-faculty/yuhua-wang",
    "author1": "Yuhua Wang",
    "author2url": "",
    "andauthor2": "",
    "author2": "",
    "author3url": "",
    "andauthor3": "",
    "author3": "",
    "gburl": "",
    "gbtext": "",
    "pubdate": "2015"
  },
  {
    "bookurl": "http://goo.gl/1yN3MW",
    "image": "//goo.gl/Yi4f7s",
    "articletitle": "",
    "articlein": "",
    "booktitle": "Cultural Conversions: Unexpected Consequences of Christian Missionary Encounters in the Middle East, Africa and South Asia",
    "author1url": "http://www.sas.upenn.edu/~hsharkey/Home.html",
    "author1": "Heather Sharkey",
    "author2url": "",
    "andauthor2": "",
    "author2": "",
    "author3url": "",
    "andauthor3": "",
    "author3": "",
    "gburl": "",
    "gbtext": "",
    "pubdate": "2013"
  },
  {
    "bookurl": "http://goo.gl/1yN3MW",
    "image": "//goo.gl/Yi4f7s",
    "articletitle": "",
    "articlein": "",
    "booktitle": "Cultural Conversions: Unexpected Consequences of Christian Missionary Encounters in the Middle East, Africa and South Asia",
    "author1url": "http://www.sas.upenn.edu/~hsharkey/Home.html",
    "author1": "Heather Sharkey",
    "author2url": "",
    "andauthor2": "",
    "author2": "",
    "author3url": "",
    "andauthor3": "",
    "author3": "",
    "gburl": "",
    "gbtext": "",
    "pubdate": "2013"
  },
  {
    "bookurl": "http://franklin.library.upenn.edu/record.html?id=FRANKLIN_6322732",
    "image": "//books.google.com/books/content?id=DADSBgAAQBAJ&printsec=frontcover&img=1&zoom=1&",
    "articletitle": "",
    "articlein": "",
    "booktitle": "Gender in Judaism and Islam : Common Lives, Uncommon Heritage",
    "author1url": "http://www.history.upenn.edu/people/faculty/firoozeh-kashani-sabet",
    "author1": "Firoozeh Kashani-Sabet",
    "author2url": "http://www.history.upenn.edu/people/faculty/beth-s-wenger",
    "andauthor2": " and ",
    "author2": "Beth S. Werger",
    "author3url": "",
    "andauthor3": "",
    "author3": "",
    "gburl": "",
    "gbtext": "",
    "pubdate": "2015"
  },
  {
    "bookurl": "http://franklin.library.upenn.edu/record.html?id=FRANKLIN_6060516",
    "image": "//books.google.com/books/content?id=4c4VAgAAQBAJ&printsec=frontcover&img=1&zoom=1&",
    "articletitle": "",
    "articlein": "",
    "booktitle": "Goethe's Ghosts: Reading and the Persistence of Literature",
    "author1url": "http://ccat.sas.upenn.edu/german/people/simon-richter",
    "author1": "Simon Richter",
    "author2url": "",
    "andauthor2": " and ",
    "author2": "Richard Block",
    "author3url": "",
    "andauthor3": "",
    "author3": "",
    "gburl": "",
    "gbtext": "",
    "pubdate": "2013"
  },
  {
    "bookurl": "http://franklin.library.upenn.edu/record.html?id=FRANKLIN_6288146",
    "image": "//books.google.com/books/content?id=w0pRBAAAQBAJ&printsec=frontcover&img=1&zoom=1&",
    "articletitle": "",
    "articlein": "",
    "booktitle": "The Greatest Empire: A Life of Seneca",
    "author1url": "https://www.classics.upenn.edu/people/emily-wilson",
    "author1": "Emily Wilson",
    "author2url": "",
    "andauthor2": "",
    "author2": "",
    "author3url": "",
    "andauthor3": "",
    "author3": "",
    "gburl": "",
    "gbtext": "",
    "pubdate": "2014"
  },
  {
    "bookurl": "http://franklin.library.upenn.edu/record.html?id=FRANKLIN_6243610",
    "image": "//books.google.com/books/content?id=dnq3oAEACAAJ&printsec=frontcover&img=1&zoom=1",
    "articletitle": "",
    "articlein": "",
    "booktitle": "Valuing the Past in the Greco-Roman World: Proceedings from the Penn-Leiden Colloquia on Ancient Values VII",
    "author1url": "https://www.classics.upenn.edu/people/james-ker",
    "author1": "James Ker",
    "author2url": "",
    "andauthor2": " and ",
    "author2": "Christoph Pieper",
    "author3url": "",
    "andauthor3": "",
    "author3": "",
    "gburl": "",
    "gbtext": "",
    "pubdate": "2014"
  },
  {
    "bookurl": "http://franklin.library.upenn.edu/record.html?id=FRANKLIN_6293046",
    "image": "//books.google.com/books/content?id=V4jroAEACAAJ&printsec=frontcover&img=1&zoom=1",
    "articletitle": "",
    "articlein": "",
    "booktitle": "Iranian Cinema in a Global Context: Policy, Politics, and Form",
    "author1url": "https://www.english.upenn.edu/people/peter-decherney",
    "author1": "Peter Decherney",
    "author2url": "",
    "andauthor2": " and ",
    "author2": "Blake Robert Atwood",
    "author3url": "",
    "andauthor3": "",
    "author3": "",
    "gburl": "",
    "gbtext": "",
    "pubdate": "2015"
  },
  {
    "bookurl": "http://dla.library.upenn.edu/dla/franklin/record.html?id=FRANKLIN_5952874&",
    "image": "//goo.gl/igOfz",
    "articletitle": "",
    "articlein": "",
    "booktitle": "The Amazing Bud Powell: Black Genius, Jazz History, and the Challenge of Bebop",
    "author1url": "https://africana.sas.upenn.edu/department/guthrie-p-ramsey-jr",
    "author1": "Guthrie P. Ramsey, Jr.",
    "author2url": "",
    "andauthor2": "",
    "author2": "",
    "author3url": "",
    "andauthor3": "",
    "author3": "",
    "gburl": "",
    "gbtext": "",
    "pubdate": "2013"
  },
  {
    "bookurl": "http://dla.library.upenn.edu/dla/franklin/record.html?id=FRANKLIN_5968278&",
    "image": "//syndetics.com/index.aspx?isbn=9780812245271/LC.GIF&client=springshare",
    "articletitle": "",
    "articlein": "",
    "booktitle": "Public Education Under Siege",
    "author1url": "http://www.history.upenn.edu/faculty/katz.shtml",
    "author1": "Michael B. Katz",
    "author2url": "http://mikerosebooks.blogspot.com/",
    "andauthor2": " and ",
    "author2": "Mike Rose, eds.",
    "author3url": "",
    "andauthor3": "",
    "author3": "",
    "gburl": "",
    "gbtext": "",
    "pubdate": "2013"
  },
  {
    "bookurl": "http://dla.library.upenn.edu/dla/franklin/record.html?id=FRANKLIN_5953096&",
    "image": "//syndetics.com/index.aspx?isbn=9780465026296/LC.GIF&client=springshare",
    "articletitle": "",
    "articlein": "",
    "booktitle": "Our Lives, Our Fortunes, and Our Sacred Honor: The Forging of American Independence, 1774-1776",
    "author1url": "http://www.history.upenn.edu/faculty/beeman.shtml",
    "author1": "Richard R. Beeman",
    "author2url": "",
    "andauthor2": "",
    "author2": "",
    "author3url": "",
    "andauthor3": "",
    "author3": "",
    "gburl": "",
    "gbtext": "",
    "pubdate": "2013"
  },
  {
    "bookurl": "http://dla.library.upenn.edu/dla/franklin/record.html?id=FRANKLIN_5957431&",
    "image": "//syndetics.com/index.aspx?isbn=9780812245004/LC.GIF&client=springshare",
    "articletitle": "",
    "articlein": "",
    "booktitle": "Trade, Land, Power: The Struggle for Eastern North America",
    "author1url": "http://www.history.upenn.edu/faculty/richter.shtml",
    "author1": "Daniel K. Richter",
    "author2url": "",
    "andauthor2": "",
    "author2": "",
    "author3url": "",
    "andauthor3": "",
    "author3": "",
    "gburl": "",
    "gbtext": "",
    "pubdate": "2013"
  },
  {
    "bookurl": "http://dla.library.upenn.edu/dla/franklin/record.html?id=FRANKLIN_5968276&",
    "image": "//images.amazon.com/images/P/0812245016.jpg",
    "articletitle": "",
    "articlein": "",
    "booktitle": "Power Sharing in Deeply Divided Places",
    "author1url": "http://www.abdn.ac.uk/socsci/staff/details.php?id=j.mcevoy",
    "author1": "Joanne McEvoy",
    "author2url": "http://www.sas.upenn.edu/polisci/people/standing-faculty/brendan-oleary",
    "andauthor2": " and ",
    "author2": "Brendan O'Leary, eds.",
    "author3url": "",
    "andauthor3": "",
    "author3": "",
    "gburl": "",
    "gbtext": "",
    "pubdate": "2013"
  },
  {
    "bookurl": "http://dla.library.upenn.edu/dla/franklin/record.html?id=FRANKLIN_5930851&",
    "image": "//syndetics.com/index.aspx?isbn=9781934536490/LC.GIF&client=springshare",
    "articletitle": "",
    "articlein": "",
    "booktitle": "Evolution of Mind, Brain, and Culture",
    "author1url": "http://philosophy.sas.upenn.edu/faculty/hatfield",
    "author1": "Gary Hatfield",
    "author2url": "https://www.sas.upenn.edu/arthistory/people/profile/holly-pittman",
    "andauthor2": " and ",
    "author2": "Holly Pittman",
    "author3url": "",
    "andauthor3": "",
    "author3": "",
    "gburl": "",
    "gbtext": "",
    "pubdate": "2013"
  },
  {
    "bookurl": "http://dla.library.upenn.edu/dla/franklin/record.html?id=FRANKLIN_5933489&",
    "image": "//syndetics.com/index.aspx?isbn=9780226925288/LC.GIF&client=springshare",
    "articletitle": "",
    "articlein": "",
    "booktitle": "Recalculating",
    "author1url": "http://www.english.upenn.edu/People/CharlesBernstein",
    "author1": "Charles Bernstein",
    "author2url": "",
    "andauthor2": "",
    "author2": "",
    "author3url": "",
    "andauthor3": "",
    "author3": "",
    "gburl": "",
    "gbtext": "",
    "pubdate": "2013"
  },
  {
    "bookurl": "http://dla.library.upenn.edu/dla/franklin/record.html?id=FRANKLIN_5953114&",
    "image": "//syndetics.com/index.aspx?isbn=9781107657410/LC.GIF&client=springshare",
    "articletitle": "",
    "articlein": "",
    "booktitle": "The Political Power of Protest: Minority Activism and Shifts in Public Policy",
    "author1url": "http://www.sas.upenn.edu/polisci/people/standing-faculty/daniel-gillion",
    "author1": "Daniel Q. Gillion",
    "author2url": "",
    "andauthor2": "",
    "author2": "",
    "author3url": "",
    "andauthor3": "",
    "author3": "",
    "gburl": "",
    "gbtext": "",
    "pubdate": "2013"
  },
  {
    "bookurl": "http://dla.library.upenn.edu/dla/franklin/record.html?id=FRANKLIN_5954850&",
    "image": "//syndetics.com/index.aspx?isbn=9780500251928/LC.GIF&client=springshare",
    "articletitle": "",
    "articlein": "",
    "booktitle": "Chinese Lives: The People Who Made a Civilization",
    "author1url": "http://www.sas.upenn.edu/ealc/mair",
    "author1": "Victor H. Mair",
    "author2url": "http://books.wwnorton.com/books/Author.aspx?id=4294972727",
    "andauthor2": ", ",
    "author2": "Sanping Chen",
    "author3url": "http://www.bl.uk/researchregister/1.10/?app_cd=RR&page_cd=RESEARCHER&l_researcher_id=88",
    "andauthor3": ", and ",
    "author3": "Frances Wood",
    "gburl": "",
    "gbtext": "",
    "pubdate": "2013"
  },
  {
    "bookurl": "http://franklin.library.upenn.edu/record.html?id=FRANKLIN_6318518",
    "image": "//books.google.com/books/content?id=H0nLoAEACAAJ&printsec=frontcover&img=1&zoom=1",
    "articletitle": "",
    "articlein": "",
    "booktitle": "Villages in the City: A Guide to South China's Informal Settlements",
    "author1url": "https://www.design.upenn.edu/city-regional-planning/graduate/people/stefan-al",
    "author1": "Stefan Al",
    "author2url": "",
    "andauthor2": "",
    "author2": "",
    "author3url": "",
    "andauthor3": "",
    "author3": "",
    "gburl": "",
    "gbtext": "",
    "pubdate": "2014"
  },
  {
    "bookurl": "http://dla.library.upenn.edu/dla/franklin/record.html?id=FRANKLIN_5914664&",
    "image": "//syndetics.com/index.aspx?isbn=9780691157047/LC.GIF&client=springshare",
    "articletitle": "",
    "articlein": "",
    "booktitle": "On the Muslim Question",
    "author1url": "http://www.sas.upenn.edu/polisci/people/standing-faculty/anne-norton",
    "author1": "Anne Norton",
    "author2url": "",
    "andauthor2": "",
    "author2": "",
    "author3url": "",
    "andauthor3": "",
    "author3": "",
    "gburl": "",
    "gbtext": "",
    "pubdate": "2013"
  },
  {
    "bookurl": "http://dla.library.upenn.edu/dla/franklin/record.html?id=FRANKLIN_5929963&",
    "image": "//syndetics.com/index.aspx?isbn=9780816677290/LC.GIF&client=springshare",
    "articletitle": "",
    "articlein": "",
    "booktitle": "On Writing with Photography",
    "author1url": "http://www.sas.upenn.edu/arthistory/people/profile/karen-beckman",
    "author1": "Karen Beckman",
    "author2url": "https://ccat.sas.upenn.edu/german/people/liliane-weissberg",
    "andauthor2": " and ",
    "author2": "Liliane Weissberg, eds.",
    "author3url": "",
    "andauthor3": "",
    "author3": "",
    "gburl": "",
    "gbtext": "",
    "pubdate": "2013"
  },
  {
    "bookurl": "http://dla.library.upenn.edu/dla/franklin/record.html?id=FRANKLIN_5939975&",
    "image": "//syndetics.com/index.aspx?isbn=9781890650810/LC.GIF&client=springshare",
    "articletitle": "",
    "articlein": "",
    "booktitle": "Sorry Was in the Woods",
    "author1url": "http://www.english.upenn.edu/People/MichelleTaransky",
    "author1": "Michelle Taransky",
    "author2url": "",
    "andauthor2": "",
    "author2": "",
    "author3url": "",
    "andauthor3": "",
    "author3": "",
    "gburl": "",
    "gbtext": "",
    "pubdate": "2013"
  },
  {
    "bookurl": "http://dla.library.upenn.edu/dla/franklin/record.html?&id=FRANKLIN_5943707&",
    "image": "//syndetics.com/index.aspx?isbn=9780521111607/LC.GIF&client=springshare",
    "articletitle": "",
    "articlein": "",
    "booktitle": "Descartes' Meditations: A Critical Guide",
    "author1url": "http://philosophy.sas.upenn.edu/faculty/detlefsen",
    "author1": "Karen Detlefsen, ed.",
    "author2url": "",
    "andauthor2": "",
    "author2": "",
    "author3url": "",
    "andauthor3": "",
    "author3": "",
    "gburl": "",
    "gbtext": "",
    "pubdate": "2013"
  },
  {
    "bookurl": "http://dla.library.upenn.edu/dla/franklin/record.html?id=FRANKLIN_5929964&",
    "image": "//syndetics.com/index.aspx?isbn=9781107028258/LC.GIF&client=springshare",
    "articletitle": "",
    "articlein": "",
    "booktitle": "The Orchestral Revolution: Haydn and the Technologies of Timbre",
    "author1url": "http://www.sas.upenn.edu/music/faculty/history.html",
    "author1": "Emily I. Dolan",
    "author2url": "",
    "andauthor2": "",
    "author2": "",
    "author3url": "",
    "andauthor3": "",
    "author3": "",
    "gburl": "",
    "gbtext": "",
    "pubdate": "2013"
  },
  {
    "bookurl": "http://dla.library.upenn.edu/dla/franklin/record.html?id=FRANKLIN_5929144&",
    "image": "//syndetics.com/index.aspx?isbn=9780745648323/LC.GIF&client=springshare",
    "articletitle": "",
    "articlein": "",
    "booktitle": "Education and Immigration",
    "author1url": "http://sociology.sas.upenn.edu/grace_kao",
    "author1": "Grace Kao",
    "author2url": "http://elizabethvaquera.com/",
    "andauthor2": ", ",
    "author2": "Elizabeth Vaquera",
    "author3url": "http://www.temple.edu/sociology/goyette/",
    "andauthor3": ", and ",
    "author3": "Kimberly Goyette",
    "gburl": "",
    "gbtext": "",
    "pubdate": "2013"
  },
  {
    "bookurl": "http://dla.library.upenn.edu/dla/franklin/record.html?id=FRANKLIN_5931360&",
    "image": "//syndetics.com/index.aspx?isbn=9781576876367/LC.GIF&client=springshare",
    "articletitle": "",
    "articlein": "",
    "booktitle": "Seven American Deaths and Disasters",
    "author1url": "http://www.english.upenn.edu/People/KennethGoldsmith",
    "author1": "Kenneth Goldsmith",
    "author2url": "",
    "andauthor2": "",
    "author2": "",
    "author3url": "",
    "andauthor3": "",
    "author3": "",
    "gburl": "",
    "gbtext": "",
    "pubdate": "2013"
  },
  {
    "bookurl": "http://dla.library.upenn.edu/dla/franklin/record.html?id=FRANKLIN_5935188&",
    "image": "//syndetics.com/index.aspx?isbn=9781137332202/LC.GIF&client=springshare",
    "articletitle": "",
    "articlein": "",
    "booktitle": "Adoption: A Brief Social and Cultural History",
    "author1url": "http://www.english.upenn.edu/People/PeterConn",
    "author1": "Peter Conn",
    "author2url": "",
    "andauthor2": "",
    "author2": "",
    "author3url": "",
    "andauthor3": "",
    "author3": "",
    "gburl": "",
    "gbtext": "",
    "pubdate": "2013"
  },
  {
    "bookurl": "http://franklin.library.upenn.edu/record.html?id=FRANKLIN_6255398",
    "image": "//books.google.com/books/content?id=bziTAwAAQBAJ&printsec=frontcover&img=1&zoom=1&",
    "articletitle": "",
    "articlein": "",
    "booktitle": "Media and the Well-Being of Children and Adolescents",
    "author1url": "https://www.asc.upenn.edu/people/faculty/amy-jordan-phd",
    "author1": "Amy B. Jordan",
    "author2url": "",
    "andauthor2": "",
    "author2": "",
    "author3url": "",
    "andauthor3": "",
    "author3": "",
    "gburl": "",
    "gbtext": "",
    "pubdate": "2014"
  },
  {
    "bookurl": "http://franklin.library.upenn.edu/record.html?id=FRANKLIN_5953114",
    "image": "//books.google.com/books/content?id=HRrYWE5RfCIC&printsec=frontcover&img=1&zoom=1&",
    "articletitle": "",
    "articlein": "",
    "booktitle": "Political Power of Protest: Minority Activism and Shifts in Public Policy",
    "author1url": "http://www.sas.upenn.edu/~dgillion/Contact%28penn%29.html",
    "author1": "Daniel Q. Gillion",
    "author2url": "",
    "andauthor2": "",
    "author2": "",
    "author3url": "",
    "andauthor3": "",
    "author3": "",
    "gburl": "",
    "gbtext": "",
    "pubdate": "2013"
  },
  {
    "bookurl": "http://franklin.library.upenn.edu/record.html?id=FRANKLIN_6001666",
    "image": "//goo.gl/sZ2iWI",
    "articletitle": "",
    "articlein": "",
    "booktitle": "Women, Pleasure, Film: What Lolas Want",
    "author1url": "http://ccat.sas.upenn.edu/german/people/simon-richter",
    "author1": "Simon Richter",
    "author2url": "",
    "andauthor2": "",
    "author2": "",
    "author3url": "",
    "andauthor3": "",
    "author3": "",
    "gburl": "http://books.google.com/books?vid=9781137309723",
    "gbtext": "Also Google Books",
    "pubdate": "2013"
  },
  {
    "bookurl": "http://franklin.library.upenn.edu/record.html?id=FRANKLIN_6091660",
    "image": "//syndetics.com/index.aspx?isbn=9780199936373/LC.GIF&client=springshare",
    "articletitle": "",
    "articlein": "",
    "booktitle": "Africa in Stereo: Modernism, Music, and Pan-African Solidarity",
    "author1url": "https://www.english.upenn.edu/People/TsitsiEllaJaji",
    "author1": "Tsitsi Jaji",
    "author2url": "",
    "andauthor2": "",
    "author2": "",
    "author3url": "",
    "andauthor3": "",
    "author3": "",
    "gburl": "",
    "gbtext": "",
    "pubdate": "2014"
  },
  {
    "bookurl": "http://franklin.library.upenn.edu/record.html?id=FRANKLIN_6224061",
    "image": "//syndetics.com/index.aspx?isbn=9780822356400/LC.GIF&client=springshare",
    "articletitle": "",
    "articlein": "",
    "booktitle": "Animating Film Theory",
    "author1url": "http://www.sas.upenn.edu/arthistory/people/profile/karen-beckman",
    "author1": "Karen Beckman",
    "author2url": "",
    "andauthor2": "",
    "author2": "",
    "author3url": "",
    "andauthor3": "",
    "author3": "",
    "gburl": "",
    "gbtext": "",
    "pubdate": "2014"
  },
  {
    "bookurl": "http://franklin.library.upenn.edu/record.html?id=FRANKLIN_6104940",
    "image": "//syndetics.com/index.aspx?isbn=9780226079189/LC.GIF&client=springshare",
    "articletitle": "",
    "articlein": "",
    "booktitle": "Boccaccio: A Critical Guide to the Complete Works",
    "author1url": "http://www.sas.upenn.edu/~vkirkham/",
    "author1": "Victoria Kirkham",
    "author2url": "https://rll.wustl.edu/people/sherberg",
    "andauthor2": ", ",
    "author2": "Michael Sherberg",
    "andauthor3": ", and ",
    "author3url": "http://theatre.ucsd.edu/people/faculty/JanetSmarr/",
    "author3": "Janet Levarie Smarr",
    "gburl": "",
    "gbtext": "",
    "pubdate": "2014"
  },
  {
    "bookurl": "http://franklin.library.upenn.edu/record.html?id=FRANKLIN_6169081",
    "image": "//syndetics.com/index.aspx?isbn=9781441146342/LC.GIF&client=springshare",
    "articletitle": "",
    "articlein": "",
    "booktitle": "Crimes of the Future: Theory and its Global Reproduction",
    "author1url": "https://www.english.upenn.edu/People/Jean-MichelRabat%C3%A9",
    "author1": "Jean-Michel Rabate ?",
    "author2url": "",
    "andauthor2": "",
    "author2": "",
    "author3url": "",
    "andauthor3": "",
    "author3": "",
    "gburl": "",
    "gbtext": "",
    "pubdate": "2014"
  },
  {
    "bookurl": "http://franklin.library.upenn.edu/record.html?id=FRANKLIN_6045660",
    "image": "//syndetics.com/index.aspx?isbn=9780801450112/LC.GIF&client=springshare",
    "articletitle": "",
    "articlein": "",
    "booktitle": "Engineering Philadelphia: The Sellers Family and the Industrial Metropolis",
    "author1url": "http://www.design.upenn.edu/people/vitiello_domenic",
    "author1": "Dominic Vitiello",
    "author2url": "",
    "andauthor2": "",
    "author2": "",
    "author3url": "",
    "andauthor3": "",
    "author3": "",
    "gburl": "",
    "gbtext": "",
    "pubdate": "2013"
  },
  {
    "bookurl": "http://franklin.library.upenn.edu/record.html?id=FRANKLIN_6105047",
    "image": "//syndetics.com/index.aspx?isbn=9780810129344/LC.GIF&client=springshare",
    "articletitle": "",
    "articlein": "",
    "booktitle": "Fugitive Objects: Sculpture and Literature in the German Nineteenth Century",
    "author1url": "http://ccat.sas.upenn.edu/german/people/catriona-macleod",
    "author1": "Catriona MacLeod",
    "author2url": "",
    "andauthor2": "",
    "author2": "",
    "author3url": "",
    "andauthor3": "",
    "author3": "",
    "gburl": "",
    "gbtext": "",
    "pubdate": "2014"
  },
  {
    "bookurl": "http://franklin.library.upenn.edu/record.html?id=FRANKLIN_6137452",
    "image": "//syndetics.com/index.aspx?isbn=9781608195916/LC.GIF&client=springshare",
    "articletitle": "",
    "articlein": "",
    "booktitle": "How Paris Became Paris: The Invention of the Modern City",
    "author1url": "http://ccat.sas.upenn.edu/roml/french/people/dejean.html",
    "author1": "Joan E. DeJean",
    "author2url": "",
    "andauthor2": "",
    "author2": "",
    "author3url": "",
    "andauthor3": "",
    "author3": "",
    "gburl": "",
    "gbtext": "",
    "pubdate": "2014"
  },
  {
    "bookurl": "http://franklin.library.upenn.edu/record.html?id=FRANKLIN_6116867",
    "image": "//syndetics.com/index.aspx?isbn=9781107031456/LC.GIF&client=springshare",
    "articletitle": "",
    "articlein": "",
    "booktitle": "Plato and the Post-Socratic Dialogue: The Return to the Philosophy of Nature",
    "author1url": "http://philosophy.sas.upenn.edu/faculty/kahn/",
    "author1": "Charles H. Kahn",
    "author2url": "",
    "andauthor2": "",
    "author2": "",
    "author3url": "",
    "andauthor3": "",
    "author3": "",
    "gburl": "",
    "gbtext": "",
    "pubdate": "2013"
  },
  {
    "bookurl": "http://franklin.library.upenn.edu/record.html?id=FRANKLIN_6098539",
    "image": "//syndetics.com/index.aspx?isbn=9780231166805/LC.GIF&client=springshare",
    "articletitle": "",
    "articlein": "",
    "booktitle": "Text to Tradition : The Nais?adhi ?yacarita and Literary Community in South Asia",
    "author1url": "https://www.southasia.upenn.edu/people/patel",
    "author1": "Deven M. Patel",
    "author2url": "",
    "andauthor2": "",
    "author2": "",
    "author3url": "",
    "andauthor3": "",
    "author3": "",
    "gburl": "",
    "gbtext": "",
    "pubdate": "2014"
  },
  {
    "bookurl": "http://franklin.library.upenn.edu/record.html?id=FRANKLIN_6110659",
    "image": "//syndetics.com/index.aspx?isbn=9781107013117/LC.GIF&client=springshare",
    "articletitle": "",
    "articlein": "",
    "booktitle": "The Cambridge Companion to Nelson Mandela",
    "author1url": "https://www.english.upenn.edu/People/RitaBarnard",
    "author1": "Rita Barnard (Editor)",
    "author2url": "",
    "andauthor2": "",
    "author2": "",
    "author3url": "",
    "andauthor3": "",
    "author3": "",
    "gburl": "",
    "gbtext": "",
    "pubdate": "2014"
  },
  {
    "bookurl": "http://franklin.library.upenn.edu/record.html?id=FRANKLIN_6318521",
    "image": "//books.google.com/books/content?id=hTMqBQAAQBAJ&printsec=frontcover&img=1&zoom=1&",
    "articletitle": "",
    "articlein": "",
    "booktitle": "Voice and V: Lessons from Acehnese",
    "author1url": "http://www.ling.upenn.edu/~jlegate/",
    "author1": "Julie Anne Legate",
    "author2url": "",
    "andauthor2": "",
    "author2": "",
    "author3url": "",
    "andauthor3": "",
    "author3": "",
    "gburl": "",
    "gbtext": "",
    "pubdate": "2014"
  },
  {
    "bookurl": "http://franklin.library.upenn.edu/record.html?id=FRANKLIN_6202155",
    "image": "//books.google.com/books/content?id=Rc0lngEACAAJ&printsec=frontcover&img=1&zoom=1",
    "articletitle": "",
    "articlein": "",
    "booktitle": "When Marx Mattered: An Intellectual Odessey",
    "author1url": "https://sociology.sas.upenn.edu/node/135",
    "author1": "Harold J. Bershady",
    "author2url": "",
    "andauthor2": "",
    "author2": "",
    "author3url": "",
    "andauthor3": "",
    "author3": "",
    "gburl": "",
    "gbtext": "",
    "pubdate": "2014"
  },
  {
    "bookurl": "http://franklin.library.upenn.edu/record.html?id=FRANKLIN_6318534",
    "image": "//books.google.com/books/content?id=80elBAAAQBAJ&printsec=frontcover&img=1&zoom=1&",
    "articletitle": "",
    "articlein": "",
    "booktitle": "The Workplace Constitution From the New Deal to the New Right",
    "author1url": "https://www.law.upenn.edu/cf/faculty/leesophi/",
    "author1": "Sophia Z. Lee",
    "author2url": "",
    "andauthor2": "",
    "author2": "",
    "author3url": "",
    "andauthor3": "",
    "author3": "",
    "gburl": "",
    "gbtext": "",
    "pubdate": "2014"
  }
]